name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.81.0
          TARGET_REPO: 1uvu.github.io
          TARGET_BRANCH: main
          TOKEN: d87ecf3c935a080e25882fb7995d8904a73b1ab5
          HUGO_ARGS: 
          CNAME: benmatselby.github.io