name: deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Hugo Deploy GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: benmatselby/hugo-deploy-gh-pages@8b85ae9dba06f933ae37854fd012574abc485ae0
      uses: benmatselby/hugo-deploy-gh-pages@v1.8.0
      with:
        # The version of hugo to use.
        hugo_version: v0.81.0-59D15C97
        # If set to `true`, use the *extended* version of hugo.
        hugo_extended: true
        # Your PAT to authorise the action to do things.
        github_token: c13678b157f54d817421f78514ccde2a778a43fe
        # The repo name you want to clone and push to.
        target_repo: 1uvu.github.io
        # The branch to push the hugo public files, default will be master branch.
        target_branch: main
        # Any extra arguments to pass to Hugo.
        hugo_args: --verbose
        # If you are defining a custom domain name for your GitHub site, put that value in this variable.
        cname: 1uvu.com
